//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektlabor.noah.planmeldung.Properties.langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pl_Covid_19_Anmeldung.Properties.langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle Backup....
        /// </summary>
        public static string backup_backup {
            get {
                return ResourceManager.GetString("backup.backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler beim durchführen von wichtigen Hintergrundprozessen aufgetreten..
        /// </summary>
        public static string backup_error {
            get {
                return ResourceManager.GetString("backup.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Authentizierung mit dem Remoteserver ist Fehlgeschlagen und das Backup konnte nicht hochgeladen werden. Bitte überprüfen sie, dass die angegebenen Daten stimmen..
        /// </summary>
        public static string backup_error_authenticate {
            get {
                return ResourceManager.GetString("backup.error.authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie diesen Fehler sehen, melden Sie ihn bitte einem Projektlaborianer.
        ///.
        /// </summary>
        public static string backup_error_disclaimer {
            get {
                return ResourceManager.GetString("backup.error.disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholen.
        /// </summary>
        public static string backup_error_retry {
            get {
                return ResourceManager.GetString("backup.error.retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Remoteserver konnte nicht erreicht werden und das Backup konnte nicht hochgeladen werden. Bitte clicken Sie auf wiederholen um den Upload erneut zu versuchen..
        /// </summary>
        public static string backup_error_upload {
            get {
                return ResourceManager.GetString("backup.error.upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melde alle Benutzer ab....
        /// </summary>
        public static string backup_logout {
            get {
                return ResourceManager.GetString("backup.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verarbeite Tagesdaten....
        /// </summary>
        public static string backup_processing {
            get {
                return ResourceManager.GetString("backup.processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Backup hoch....
        /// </summary>
        public static string backup_upload {
            get {
                return ResourceManager.GetString("backup.upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichere das Profil....
        /// </summary>
        public static string main_admin_edituser_loading {
            get {
                return ResourceManager.GetString("main.admin.edituser.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        public static string main_admin_edituser_save {
            get {
                return ResourceManager.GetString("main.admin.edituser.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der ausgewählte Nutzer konnte nicht gefunden werden? Bitte versuchen Sie erneut ihn auszuwählen..
        /// </summary>
        public static string main_admin_edituser_select_error_not_found_text {
            get {
                return ResourceManager.GetString("main.admin.edituser.select.error.not_found.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer nicht gefunden.
        /// </summary>
        public static string main_admin_edituser_select_error_not_found_title {
            get {
                return ResourceManager.GetString("main.admin.edituser.select.error.not_found.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Benutzer....
        /// </summary>
        public static string main_admin_edituser_select_loading {
            get {
                return ResourceManager.GetString("main.admin.edituser.select.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil editieren.
        /// </summary>
        public static string main_admin_edituser_title {
            get {
                return ResourceManager.GetString("main.admin.edituser.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        public static string main_admin_login_button {
            get {
                return ResourceManager.GetString("main.admin.login.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort eingeben.
        /// </summary>
        public static string main_admin_login_field {
            get {
                return ResourceManager.GetString("main.admin.login.field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen im Admin-Panel.
        /// </summary>
        public static string main_admin_title {
            get {
                return ResourceManager.GetString("main.admin.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinde zur Datenbank....
        /// </summary>
        public static string main_database_connecting {
            get {
                return ResourceManager.GetString("main.database.connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zu Datenbank hergestellt werden. Bitte versuchen Sie versichern Sie sich, dass das Gerät einen validen Netzwerkzugang hat und die Datenbank erreichen kann..
        /// </summary>
        public static string main_database_error_connect_text {
            get {
                return ResourceManager.GetString("main.database.error.connect.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim verbinden.
        /// </summary>
        public static string main_database_error_connect_title {
            get {
                return ResourceManager.GetString("main.database.error.connect.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zu Datenbank hergestellt werden. Bitte versuchen Sie es erneut. Sollte diese Nachricht weiterhin angezeigt werden fragen Sie bitte einen Projektlaborianer..
        /// </summary>
        public static string main_database_error_connect_user_text {
            get {
                return ResourceManager.GetString("main.database.error.connect.user.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbank hat die Verbindung abgebrochen. Bitte überprüfen Sie, dass Sie der Nutzername und das Passwort stimmen und das die Datenbank exestiert..
        /// </summary>
        public static string main_database_error_credentials_text {
            get {
                return ResourceManager.GetString("main.database.error.credentials.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafte Anmeldeinformationen angegeben.
        /// </summary>
        public static string main_database_error_credentials_title {
            get {
                return ResourceManager.GetString("main.database.error.credentials.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein unerwarteter Fehler aufgetreten. Bitte sagen Sie sofort einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_error_fatal_text {
            get {
                return ResourceManager.GetString("main.error.fatal.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritischer Fehler aufgetreten.
        /// </summary>
        public static string main_error_fatal_title {
            get {
                return ResourceManager.GetString("main.error.fatal.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string main_login_button_end {
            get {
                return ResourceManager.GetString("main.login.button.end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string main_login_button_start {
            get {
                return ResourceManager.GetString("main.login.button.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlassen.
        /// </summary>
        public static string main_login_field_end {
            get {
                return ResourceManager.GetString("main.login.field.end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string main_login_field_lastname {
            get {
                return ResourceManager.GetString("main.login.field.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betreten.
        /// </summary>
        public static string main_login_field_start {
            get {
                return ResourceManager.GetString("main.login.field.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string main_login_fields_firstname {
            get {
                return ResourceManager.GetString("main.login.fields.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden....
        /// </summary>
        public static string main_login_loading {
            get {
                return ResourceManager.GetString("main.login.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden....
        /// </summary>
        public static string main_login_loading_logout {
            get {
                return ResourceManager.GetString("main.login.loading.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen    (Erfolgreich angemeldet).
        /// </summary>
        public static string main_login_rfid_success_title_login {
            get {
                return ResourceManager.GetString("main.login.rfid.success.title.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tschüss    (Erfolgreich abgemeldet).
        /// </summary>
        public static string main_login_rfid_success_title_logout {
            get {
                return ResourceManager.GetString("main.login.rfid.success.title.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Benutzer....
        /// </summary>
        public static string main_login_select_loading {
            get {
                return ResourceManager.GetString("main.login.select.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string main_login_title {
            get {
                return ResourceManager.GetString("main.login.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string main_popup_close {
            get {
                return ResourceManager.GetString("main.popup.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut versuchen.
        /// </summary>
        public static string main_popup_retrie {
            get {
                return ResourceManager.GetString("main.popup.retrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich akzeptiere, dass meine Daten gespeichert werden..
        /// </summary>
        public static string main_register_accept {
            get {
                return ResourceManager.GetString("main.register.accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Daten werden von uns über die Zeit der Covid-19 Pandemie gespeichert. Wenn Sie angeben, dass ihre Daten nach 6 Wochen gelöscht werden sollen, werden diese innerhalb von 4-6 Wochen von unserem System entfernt. Ihre Daten werden von uns nicht weitergegeben und sind nur von Administratoren einsehbar. Gespeichert werden ihre Daten auf unserem Server im Projektlabor und auf einem Goneo-server welcher in Frankfurt steht..
        /// </summary>
        public static string main_register_accept_text {
            get {
                return ResourceManager.GetString("main.register.accept.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string main_register_button {
            get {
                return ResourceManager.GetString("main.register.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername wird bereits verwendet. Bitte geben Sie ihren Namen an. Oder ändern Sie ihn etwas ab um Verwirrung zu vermeiden..
        /// </summary>
        public static string main_register_error_name {
            get {
                return ResourceManager.GetString("main.register.error.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser RFIC-Code wird bereits verwendet. Bitte verwenden Sie einen anderen Code oder eine andere Karte..
        /// </summary>
        public static string main_register_error_rfid {
            get {
                return ResourceManager.GetString("main.register.error.rfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Registrieren.
        /// </summary>
        public static string main_register_error_title {
            get {
                return ResourceManager.GetString("main.register.error.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registriere....
        /// </summary>
        public static string main_register_loading {
            get {
                return ResourceManager.GetString("main.register.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben sich erfolgreich registriert. Bitte melden sie sich jetzt noch an und wenn sie gehen wieder ab..
        /// </summary>
        public static string main_register_success_text {
            get {
                return ResourceManager.GetString("main.register.success.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich registriert.
        /// </summary>
        public static string main_register_success_title {
            get {
                return ResourceManager.GetString("main.register.success.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string main_register_title {
            get {
                return ResourceManager.GetString("main.register.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte kein Benutzer mit dieser RFID gefunden werden. Bitte versichern Sie sich, dass Sie die richtige Karte gescannt haben und versuchen Sie erneut die Karte zu scannen. Sollt diese Meldung weiterhin angezeigt werden, fragen Sie einen Projektlaborianer ob er ihrem Profil die RFID-Karte zuweist..
        /// </summary>
        public static string main_rfid_error_loading_text {
            get {
                return ResourceManager.GetString("main.rfid.error.loading.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzer konnte nicht gefunden werden.
        /// </summary>
        public static string main_rfid_error_loading_title {
            get {
                return ResourceManager.GetString("main.rfid.error.loading.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte kein angeschlossener RFID-Scanner gefunden werden. Bitte versichern Sie sich, dass dieser angeschlossen ist. Es kann helfen den Scanner einmal raus und wieder ein zu stecken..
        /// </summary>
        public static string main_rfid_error_port_not_found_text {
            get {
                return ResourceManager.GetString("main.rfid.error.port_not_found.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID-Scanner wurde nicht gefunden..
        /// </summary>
        public static string main_rfid_error_port_not_found_title {
            get {
                return ResourceManager.GetString("main.rfid.error.port_not_found.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche Nutzer....
        /// </summary>
        public static string main_rfid_loading {
            get {
                return ResourceManager.GetString("main.rfid.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Account soll nach 6 Wochen gelöscht werden..
        /// </summary>
        public static string ui_register_autodeleteaccount {
            get {
                return ResourceManager.GetString("ui.register.autodeleteaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir versichern, dass ihr Konto nach 4 und allerspätestens 6 Wochen gelöscht wird. Wenn Sie innerhalb dieser Zeitspanne im Projektlabor waren, wird diese Zeit zurückgesetzt..
        /// </summary>
        public static string ui_register_autodeleteaccount_text {
            get {
                return ResourceManager.GetString("ui.register.autodeleteaccount.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannen.
        /// </summary>
        public static string ui_register_button_scan {
            get {
                return ResourceManager.GetString("ui.register.button.scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (Optional).
        /// </summary>
        public static string ui_register_email {
            get {
                return ResourceManager.GetString("ui.register.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ui_register_error_street_number {
            get {
                return ResourceManager.GetString("ui.register.error.street_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string ui_register_firstname {
            get {
                return ResourceManager.GetString("ui.register.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string ui_register_lastname {
            get {
                return ResourceManager.GetString("ui.register.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wohnort.
        /// </summary>
        public static string ui_register_location {
            get {
                return ResourceManager.GetString("ui.register.location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine valide Email-Adresse an..
        /// </summary>
        public static string ui_register_opterror_email {
            get {
                return ResourceManager.GetString("ui.register.opterror.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string ui_register_plz {
            get {
                return ResourceManager.GetString("ui.register.plz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID-Code (Optional).
        /// </summary>
        public static string ui_register_rfid {
            get {
                return ResourceManager.GetString("ui.register.rfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halten Sie ihre RFID-Karte oder ihr Handy mit der RFID-App an den Scanner und lassen Sie ihre Karte scannen..
        /// </summary>
        public static string ui_register_rfid_text {
            get {
                return ResourceManager.GetString("ui.register.rfid.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte scannen sie ihre RFID-Karte.
        /// </summary>
        public static string ui_register_rfid_title {
            get {
                return ResourceManager.GetString("ui.register.rfid.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string ui_register_street {
            get {
                return ResourceManager.GetString("ui.register.street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        public static string ui_register_street_number {
            get {
                return ResourceManager.GetString("ui.register.street_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon (Optional).
        /// </summary>
        public static string ui_register_telephone {
            get {
                return ResourceManager.GetString("ui.register.telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erforderlich.
        /// </summary>
        public static string ui_registerinput_opterror_default {
            get {
                return ResourceManager.GetString("ui.registerinput.opterror.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhaft.
        /// </summary>
        public static string ui_registerinput_regexerror_default {
            get {
                return ResourceManager.GetString("ui.registerinput.regexerror.default", resourceCulture);
            }
        }
    }
}
