//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektlabor.noah.planmeldung.Properties.langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pl_Covid_19_Anmeldung.Properties.langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        public static string config_button_newpw {
            get {
                return ResourceManager.GetString("config.button.newpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig.
        /// </summary>
        public static string config_button_reset {
            get {
                return ResourceManager.GetString("config.button.reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string config_button_save {
            get {
                return ResourceManager.GetString("config.button.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rohmaterial Kopieren.
        /// </summary>
        public static string config_currepted_copy {
            get {
                return ResourceManager.GetString("config.currepted.copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr eingegebener Schlüssel ist richtig und die Datei konnte geladen werden.
        ///Leider das Dateiformat kapput und kann nicht geladen werden.
        ///Möchten Sie eine neue Konifiguration anlegen?
        ///Unterhalb können sie auch das Rohmaterial, welches geladen werden konnte Kopieren..
        /// </summary>
        public static string config_currupted_info {
            get {
                return ResourceManager.GetString("config.currupted.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string config_currupted_no {
            get {
                return ResourceManager.GetString("config.currupted.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration is Fehlerhaft.
        /// </summary>
        public static string config_currupted_title {
            get {
                return ResourceManager.GetString("config.currupted.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu erstellen.
        /// </summary>
        public static string config_currupted_yes {
            get {
                return ResourceManager.GetString("config.currupted.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP/Domain (Remote Server).
        /// </summary>
        public static string config_host {
            get {
                return ResourceManager.GetString("config.host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string config_loaderr_close {
            get {
                return ResourceManager.GetString("config.loaderr.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim laden.
        /// </summary>
        public static string config_loaderr_title {
            get {
                return ResourceManager.GetString("config.loaderr.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim erstellen der Konfiguration.
        /// </summary>
        public static string config_new_error {
            get {
                return ResourceManager.GetString("config.new.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string config_new_error_button {
            get {
                return ResourceManager.GetString("config.new.error.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein neues Passwort an..
        /// </summary>
        public static string config_new_pass_text {
            get {
                return ResourceManager.GetString("config.new.pass.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        public static string config_new_pass_title {
            get {
                return ResourceManager.GetString("config.new.pass.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string config_newpw_no {
            get {
                return ResourceManager.GetString("config.newpw.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort eingeben.
        /// </summary>
        public static string config_newpw_title {
            get {
                return ResourceManager.GetString("config.newpw.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string config_newpw_yes {
            get {
                return ResourceManager.GetString("config.newpw.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Konfigurationsdatei gefunden, möchten Sie eine neue erstellen?.
        /// </summary>
        public static string config_notexisting_info {
            get {
                return ResourceManager.GetString("config.notexisting.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string config_notexisting_no {
            get {
                return ResourceManager.GetString("config.notexisting.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationsdatei existiert nicht.
        /// </summary>
        public static string config_notexisting_title {
            get {
                return ResourceManager.GetString("config.notexisting.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string config_notexisting_yes {
            get {
                return ResourceManager.GetString("config.notexisting.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string config_pass_cancle {
            get {
                return ResourceManager.GetString("config.pass.cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        public static string config_pass_ok {
            get {
                return ResourceManager.GetString("config.pass.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort benötigt.
        /// </summary>
        public static string config_pass_title {
            get {
                return ResourceManager.GetString("config.pass.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port-Nummer (Remote Server).
        /// </summary>
        public static string config_port {
            get {
                return ResourceManager.GetString("config.port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA-Schlüssel.
        /// </summary>
        public static string config_rsa {
            get {
                return ResourceManager.GetString("config.rsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string config_save_button {
            get {
                return ResourceManager.GetString("config.save.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafter Schlüssel (Private Key).
        /// </summary>
        public static string config_save_key {
            get {
                return ResourceManager.GetString("config.save.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafter Port.
        /// </summary>
        public static string config_save_port {
            get {
                return ResourceManager.GetString("config.save.port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Fehler.
        /// </summary>
        public static string config_save_unknown {
            get {
                return ResourceManager.GetString("config.save.unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration.
        /// </summary>
        public static string config_title {
            get {
                return ResourceManager.GetString("config.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut versuchen.
        /// </summary>
        public static string config_wrongpw_retry {
            get {
                return ResourceManager.GetString("config.wrongpw.retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Passwort.
        /// </summary>
        public static string config_wrongpw_title {
            get {
                return ResourceManager.GetString("config.wrongpw.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichere das Profil....
        /// </summary>
        public static string main_admin_edituser_loading {
            get {
                return ResourceManager.GetString("main.admin.edituser.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        public static string main_admin_edituser_save {
            get {
                return ResourceManager.GetString("main.admin.edituser.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der ausgewählte Nutzer konnte nicht gefunden werden? Bitte versuchen Sie erneut ihn auszuwählen..
        /// </summary>
        public static string main_admin_edituser_select_error_not_found_text {
            get {
                return ResourceManager.GetString("main.admin.edituser.select.error.not_found.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer nicht gefunden.
        /// </summary>
        public static string main_admin_edituser_select_error_not_found_title {
            get {
                return ResourceManager.GetString("main.admin.edituser.select.error.not_found.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Benutzer....
        /// </summary>
        public static string main_admin_edituser_select_loading {
            get {
                return ResourceManager.GetString("main.admin.edituser.select.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil editieren.
        /// </summary>
        public static string main_admin_edituser_title {
            get {
                return ResourceManager.GetString("main.admin.edituser.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        public static string main_admin_login_button {
            get {
                return ResourceManager.GetString("main.admin.login.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort eingeben.
        /// </summary>
        public static string main_admin_login_field {
            get {
                return ResourceManager.GetString("main.admin.login.field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen im Admin-Panel.
        /// </summary>
        public static string main_admin_title {
            get {
                return ResourceManager.GetString("main.admin.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein unerwarteter Fehler aufgetreten. Bitte sagen Sie sofort einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_error_fatal_text {
            get {
                return ResourceManager.GetString("main.error.fatal.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritischer Fehler aufgetreten.
        /// </summary>
        public static string main_error_fatal_title {
            get {
                return ResourceManager.GetString("main.error.fatal.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string main_login_button_end {
            get {
                return ResourceManager.GetString("main.login.button.end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string main_login_button_start {
            get {
                return ResourceManager.GetString("main.login.button.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string main_login_error_button_ok {
            get {
                return ResourceManager.GetString("main.login.error.button.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlassen.
        /// </summary>
        public static string main_login_field_end {
            get {
                return ResourceManager.GetString("main.login.field.end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string main_login_field_lastname {
            get {
                return ResourceManager.GetString("main.login.field.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betreten.
        /// </summary>
        public static string main_login_field_start {
            get {
                return ResourceManager.GetString("main.login.field.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string main_login_fields_firstname {
            get {
                return ResourceManager.GetString("main.login.fields.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer konnte nicht gefunden werden.
        ///Bitte versuchen Sie erneut ihren Benutzer auszuwählen.
        ///Sollte weiterhin dies Meldung kommen, geben Sie bitte einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_login_get_error_not_found_text {
            get {
                return ResourceManager.GetString("main.login.get.error.not_found.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer nicht gefunden.
        /// </summary>
        public static string main_login_get_error_not_found_title {
            get {
                return ResourceManager.GetString("main.login.get.error.not_found.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden....
        /// </summary>
        public static string main_login_loading {
            get {
                return ResourceManager.GetString("main.login.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden....
        /// </summary>
        public static string main_login_loading_logout {
            get {
                return ResourceManager.GetString("main.login.loading.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind anscheinend immer noch angemeldet.
        ///Bitte wählen Sie ihren Benutzer noch einmal aus um sicher zu gehen..
        /// </summary>
        public static string main_login_login_error_loggedin_text {
            get {
                return ResourceManager.GetString("main.login.login.error.loggedin.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ist immer noch angemeldet.
        /// </summary>
        public static string main_login_login_error_loggedin_title {
            get {
                return ResourceManager.GetString("main.login.login.error.loggedin.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer konnte nicht gefunden werden.
        ///Bitte versuchen Sie erneut ihren Benutzer auszuwählen.
        ///Sollte weiterhin dies Meldung kommen, geben Sie bitte einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_login_login_error_not_found_text {
            get {
                return ResourceManager.GetString("main.login.login.error.not_found.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer nicht gefunden.
        /// </summary>
        public static string main_login_login_error_not_found_title {
            get {
                return ResourceManager.GetString("main.login.login.error.not_found.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind anscheinend nicht mehr angemeldet.
        ///Bitte wählen Sie ihren Benutzer noch einmal aus um sicher zu gehen..
        /// </summary>
        public static string main_login_logout_error_loggedout_text {
            get {
                return ResourceManager.GetString("main.login.logout.error.loggedout.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ist bereits abgemeldet.
        /// </summary>
        public static string main_login_logout_error_loggedout_title {
            get {
                return ResourceManager.GetString("main.login.logout.error.loggedout.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer konnte nicht gefunden werden.
        ///Bitte versuchen Sie erneut ihren Benutzer auszuwählen.
        ///Sollte weiterhin dies Meldung kommen, geben Sie bitte einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_login_logout_error_not_found_text {
            get {
                return ResourceManager.GetString("main.login.logout.error.not_found.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer nicht gefunden.
        /// </summary>
        public static string main_login_logout_error_not_found_title {
            get {
                return ResourceManager.GetString("main.login.logout.error.not_found.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen    (Erfolgreich angemeldet).
        /// </summary>
        public static string main_login_rfid_success_title_login {
            get {
                return ResourceManager.GetString("main.login.rfid.success.title.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tschüss    (Erfolgreich abgemeldet).
        /// </summary>
        public static string main_login_rfid_success_title_logout {
            get {
                return ResourceManager.GetString("main.login.rfid.success.title.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Benutzer....
        /// </summary>
        public static string main_login_select_loading {
            get {
                return ResourceManager.GetString("main.login.select.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string main_login_title {
            get {
                return ResourceManager.GetString("main.login.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string main_popup_close {
            get {
                return ResourceManager.GetString("main.popup.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut versuchen.
        /// </summary>
        public static string main_popup_retrie {
            get {
                return ResourceManager.GetString("main.popup.retrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich akzeptiere, dass meine Daten gespeichert werden..
        /// </summary>
        public static string main_register_accept {
            get {
                return ResourceManager.GetString("main.register.accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Daten werden von uns über die Zeit der Covid-19 Pandemie gespeichert. Wenn Sie angeben, dass ihre Daten nach 6 Wochen gelöscht werden sollen, werden diese innerhalb von 4-6 Wochen von unserem System entfernt. Ihre Daten werden von uns nicht weitergegeben und sind nur von Administratoren einsehbar. Gespeichert werden ihre Daten auf unserem Server im Projektlabor und auf einem Goneo-server, welcher in Frankfurt steht..
        /// </summary>
        public static string main_register_accept_text {
            get {
                return ResourceManager.GetString("main.register.accept.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string main_register_button {
            get {
                return ResourceManager.GetString("main.register.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername wird bereits verwendet.
        ///Bitte geben Sie ihren Namen an. Oder ändern Sie ihn etwas ab um Verwirrung zu vermeiden..
        /// </summary>
        public static string main_register_error_name {
            get {
                return ResourceManager.GetString("main.register.error.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser RFIC-Code wird bereits verwendet. Bitte verwenden Sie einen anderen Code oder eine andere Karte..
        /// </summary>
        public static string main_register_error_rfid {
            get {
                return ResourceManager.GetString("main.register.error.rfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Registrieren.
        /// </summary>
        public static string main_register_error_title {
            get {
                return ResourceManager.GetString("main.register.error.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registriere....
        /// </summary>
        public static string main_register_loading {
            get {
                return ResourceManager.GetString("main.register.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben sich erfolgreich registriert. Bitte melden sie sich jetzt noch an und wenn sie gehen wieder ab..
        /// </summary>
        public static string main_register_success_text {
            get {
                return ResourceManager.GetString("main.register.success.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich registriert.
        /// </summary>
        public static string main_register_success_title {
            get {
                return ResourceManager.GetString("main.register.success.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string main_register_title {
            get {
                return ResourceManager.GetString("main.register.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist wärend der Verbindung zum Remoteserver ein Verifizierungsfehler aufgetreten. Bitte versuchen Sie es erneut. Sollte es weiterhin nicht funktionieren, geben Sie bitte einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_request_error_auth_info {
            get {
                return ResourceManager.GetString("main.request.error.auth.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifizierungsfehler.
        /// </summary>
        public static string main_request_error_auth_title {
            get {
                return ResourceManager.GetString("main.request.error.auth.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string main_request_error_button {
            get {
                return ResourceManager.GetString("main.request.error.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Serverseitige-schnittstelle konnte nicht gefunden werden. Bitte sagen Sie einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_request_error_handler_info {
            get {
                return ResourceManager.GetString("main.request.error.handler.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler nicht bekannt.
        /// </summary>
        public static string main_request_error_handler_title {
            get {
                return ResourceManager.GetString("main.request.error.handler.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung zum Remoteserver konnte nicht hergestellt werden oder wurde verloren. Bitte versuchen Sie es erneut. Sollte es weiterhin nicht funktionieren, geben Sie bitte einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_request_error_io_info {
            get {
                return ResourceManager.GetString("main.request.error.io.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung verloren.
        /// </summary>
        public static string main_request_error_io_title {
            get {
                return ResourceManager.GetString("main.request.error.io.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Schlüsselfehler aufgetreten..
        /// </summary>
        public static string main_request_error_technical_authkey_text {
            get {
                return ResourceManager.GetString("main.request.error.technical.authkey.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Server hat einen Auth-fehler zurückgegeben..
        /// </summary>
        public static string main_request_error_technical_authserver_text {
            get {
                return ResourceManager.GetString("main.request.error.technical.authserver.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dem Server ist ein Fehler mit der Datenbank aufgetreten..
        /// </summary>
        public static string main_request_error_technical_database_text {
            get {
                return ResourceManager.GetString("main.request.error.technical.database.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Server hat einen Handler-fehler zurückgegeben..
        /// </summary>
        public static string main_request_error_technical_handler_text {
            get {
                return ResourceManager.GetString("main.request.error.technical.handler.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Server zu wenig oder falsche Daten gesendet um die Anfrage zu verarbeiten..
        /// </summary>
        public static string main_request_error_technical_lessreturn_text {
            get {
                return ResourceManager.GetString("main.request.error.technical.lessreturn.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein technischer Fehler aufgetreten, bitte geben Sie einem Projektlaborianer bescheid.
        ///Beschreibung:
        ///.
        /// </summary>
        public static string main_request_error_technical_text {
            get {
                return ResourceManager.GetString("main.request.error.technical.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technischer Fehler.
        /// </summary>
        public static string main_request_error_technical_title {
            get {
                return ResourceManager.GetString("main.request.error.technical.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein unbekannter Fehler aufgetreten. Bitte logs anschauen und ggf. kritisches Loggen benutzen..
        /// </summary>
        public static string main_request_error_technical_unknown_text {
            get {
                return ResourceManager.GetString("main.request.error.technical.unknown.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist eine unbekannter Fehler aufgetreten. Bitte geben Sie einem Projektlaborianer bescheid..
        /// </summary>
        public static string main_request_error_unknown_info {
            get {
                return ResourceManager.GetString("main.request.error.unknown.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Fehler.
        /// </summary>
        public static string main_request_error_unknown_title {
            get {
                return ResourceManager.GetString("main.request.error.unknown.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte kein Benutzer mit dieser RFID gefunden werden. Bitte versichern Sie sich, dass Sie die richtige Karte gescannt haben und versuchen Sie erneut die Karte zu scannen. Sollt diese Meldung weiterhin angezeigt werden, fragen Sie einen Projektlaborianer ob er ihrem Profil die RFID-Karte zuweist..
        /// </summary>
        public static string main_rfid_error_loading_text {
            get {
                return ResourceManager.GetString("main.rfid.error.loading.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzer konnte nicht gefunden werden.
        /// </summary>
        public static string main_rfid_error_loading_title {
            get {
                return ResourceManager.GetString("main.rfid.error.loading.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte kein angeschlossener RFID-Scanner gefunden werden. Bitte versichern Sie sich, dass dieser angeschlossen ist. Es kann helfen den Scanner einmal raus und wieder ein zu stecken..
        /// </summary>
        public static string main_rfid_error_port_not_found_text {
            get {
                return ResourceManager.GetString("main.rfid.error.port_not_found.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID-Scanner wurde nicht gefunden..
        /// </summary>
        public static string main_rfid_error_port_not_found_title {
            get {
                return ResourceManager.GetString("main.rfid.error.port_not_found.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche Nutzer....
        /// </summary>
        public static string main_rfid_loading {
            get {
                return ResourceManager.GetString("main.rfid.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Account soll nach 6 Wochen gelöscht werden..
        /// </summary>
        public static string ui_register_autodeleteaccount {
            get {
                return ResourceManager.GetString("ui.register.autodeleteaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir versichern, dass ihr Konto nach 4 und allerspätestens 6 Wochen gelöscht wird. Wenn Sie innerhalb dieser Zeitspanne im Projektlabor waren, wird diese Zeit zurückgesetzt..
        /// </summary>
        public static string ui_register_autodeleteaccount_text {
            get {
                return ResourceManager.GetString("ui.register.autodeleteaccount.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannen.
        /// </summary>
        public static string ui_register_button_scan {
            get {
                return ResourceManager.GetString("ui.register.button.scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (Optional).
        /// </summary>
        public static string ui_register_email {
            get {
                return ResourceManager.GetString("ui.register.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ui_register_error_street_number {
            get {
                return ResourceManager.GetString("ui.register.error.street_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string ui_register_firstname {
            get {
                return ResourceManager.GetString("ui.register.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string ui_register_lastname {
            get {
                return ResourceManager.GetString("ui.register.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wohnort.
        /// </summary>
        public static string ui_register_location {
            get {
                return ResourceManager.GetString("ui.register.location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine valide Email-Adresse an..
        /// </summary>
        public static string ui_register_opterror_email {
            get {
                return ResourceManager.GetString("ui.register.opterror.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string ui_register_plz {
            get {
                return ResourceManager.GetString("ui.register.plz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID-Code (Optional).
        /// </summary>
        public static string ui_register_rfid {
            get {
                return ResourceManager.GetString("ui.register.rfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halten Sie ihre RFID-Karte oder ihr Handy mit der RFID-App an den Scanner und lassen Sie ihre Karte scannen..
        /// </summary>
        public static string ui_register_rfid_text {
            get {
                return ResourceManager.GetString("ui.register.rfid.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte scannen sie ihre RFID-Karte.
        /// </summary>
        public static string ui_register_rfid_title {
            get {
                return ResourceManager.GetString("ui.register.rfid.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string ui_register_street {
            get {
                return ResourceManager.GetString("ui.register.street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        public static string ui_register_street_number {
            get {
                return ResourceManager.GetString("ui.register.street_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon (Optional).
        /// </summary>
        public static string ui_register_telephone {
            get {
                return ResourceManager.GetString("ui.register.telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erforderlich.
        /// </summary>
        public static string ui_registerinput_opterror_default {
            get {
                return ResourceManager.GetString("ui.registerinput.opterror.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhaft.
        /// </summary>
        public static string ui_registerinput_regexerror_default {
            get {
                return ResourceManager.GetString("ui.registerinput.regexerror.default", resourceCulture);
            }
        }
    }
}
